
export default [
  {displayString:'邪銀三郎', inputString:'yokoshimaginzaburou'},
  {displayString:'Release', inputString:'release'},
  {displayString:'FAIL HARDER', inputString:'failharder'},
  {displayString:'サミュエル', inputString:'samuel'},
  {displayString:'労働組合', inputString:'roudoukumiai'},
  {displayString:'テストしたい', inputString:'testshitai'},
  {displayString:'たびに出よう', inputString:'tabinideyou'},
  {displayString:'ランチはちくわ', inputString:'ranchihachikuwa'},
  {displayString:'ランチパック', inputString:'ranchipakku'},
  {displayString:'マージボタンをおしただけ', inputString:'ma-jibotanwooshitadake'},
  {displayString:'何もしてないのにこわれた', inputString:'nanimoshitenainonikowareta'},
  {displayString:'まほうで動いている', inputString:'mahoudeugoiteiru'},
  {displayString:'転職してラッパーになる', inputString:'tenshokushiterappa-ninaru'},
  {displayString:'単価を上げてください', inputString:'tankawoagetekudasai'},
  {displayString:'今日もストゼロを飲む', inputString:'kyoumosutozerowonomu'},
  {displayString:'リーダブルコードよんだかい', inputString:'ri-daburuko-doyondakai'},
  {displayString:'夏となればまた格別', inputString:'natsutonarebamatakakubetsu'},
  {displayString:'お寿司がたべたい', inputString:'osushigatabetai'},
  {displayString:'会いたくて震える', inputString:'aitakutefurueru'},
  {displayString:'あっさりしたものが食べたい', inputString:'assarishitamonogatabetai'},
  {displayString:'歳かな', inputString:'toshikana'},
  {displayString:'マスターにプッシュしよう', inputString:'masuta-nipusshushiyou'},
]

